### ISSUE TITLE
Precisamos Dar Partida neste projeto também

### ISSUE THREAD

**Issue by Pedro2869** [ZynkePartnership/Lopenk#5]
Vamos resolver algumas coisas antes de colocarmos a mão na massa

**Comment by LoriaLawrenceZ** [comment]
Consegue desenvolver?

**Comment by LoriaLawrenceZ** [comment]
Pera, pq tu criou outro proheto?
 Era só fazer no lopenk la q ja existekk

**Comment by LoriaLawrenceZ** [comment]
@Pedro2869 
Por outro projeto, falo aquele sem nome específico, aquele Pedro's project e nao sei oq, tipo, oq a gente precisa já tá criado, q é esse de advocacia e o lopenk (e o agrodrone, só q é daq do senai), pode deletar esse quarto projeto sem nada dentro?
